### ISSUE TITLE
Breaks on Magit 2.1

### ISSUE THREAD

**Issue by PythonNut** [magit/magit-filenotify#10]
Same as #9 but under different conditions. (I don't know why). `magit-filenotify` triggers its own update conditions, causing an infinite loop.

**Comment by ruediger** [comment]
What conditions? Works for me with magit 2.1.

**Comment by PythonNut** [comment]
@ruediger I couldn't find any conditions where this did _not_ happen.

**Comment by ruediger** [comment]
What GNU Emacs version? What OS? What's the value of `file-notify--library`? Try running `trace-function` on `magit-filenotify--callback` to see for what file it gets called.

**Comment by PythonNut** [comment]
* `25.1`
* Arch Linux
* `gfilenotify`

But oddly, it doesn't reproduce for me.
