### ISSUE TITLE
Excessive repeated revert messages

### ISSUE THREAD

**Issue by tsdh** [magit/magit-filenotify#11]
I just started using `magit-filenotify` (current MELPA version) together with magit (post 2.1.0 from MELPA) in Emacs 25 from Git (as of today).  It's really nice, the magit status buffer is always up-to-date.

But: I work on some latex document residing in some git repository.  Whenever I recompile it (no matter if I actually changed the tex file), I get a big amount of messages.

```
LaTeX: successfully formatted {6} pages [2 times]
Reverting (up to) 2 file-visiting buffer(s)...
(No buffers need to be reverted)
Reverting (up to) 2 file-visiting buffer(s)...
(No buffers need to be reverted)
[this repeats a good dozens of times; there are 149 lines from the LaTeX message
 down to the end of the revert messages, so more than 70 try-revert/nothing to be
 done cycles]
```

Here's the value of `magit-filenotify-data`:

```
magit-filenotify-data is a variable defined in ‘magit-filenotify.el’.
Its value is shown below.

Documentation:
A hash table to map watch-descriptors to a list (DIRECTORY STATUS-BUFFER).

Value:
#s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data
	      (13726044
	       ("/home/horn/Repos/uni/ttc15-model-execution-funnyqt/" #<killed buffer>)
	       13625136
	       ("/home/horn/Repos/uni/ttc15-model-execution-funnyqt/" #<buffer *magit: ~/Repos/uni/ttc15-model-execution-funnyqt/*>)
	       13717556
	       ("/home/horn/Repos/uni/ttc15-model-execution-funnyqt/resources/" #<killed buffer>)
	       13773344
	       ("/home/horn/Repos/uni/ttc15-model-execution-funnyqt/src/ttc15_model_execution_funnyqt/" #<killed buffer>)
	       13768668
	       ("/home/horn/Repos/uni/ttc15-model-execution-funnyqt/test/model/" #<killed buffer>)
	       13624944
	       ("/home/horn/Repos/uni/ttc15-model-execution-funnyqt/test/ttc15_model_execution_funnyqt/" #<killed buffer>)
	       13641328
	       ("/home/horn/Repos/uni/ttc15-model-execution-funnyqt/doc/" #<buffer *magit: ~/Repos/uni/ttc15-model-execution-funnyqt/*>)
	       13778552
	       ("/home/horn/Repos/uni/ttc15-model-execution-funnyqt/resources/" #<buffer *magit: ~/Repos/uni/ttc15-model-execution-funnyqt/*>)
	       12253856
	       ("/home/horn/Repos/uni/ttc15-model-execution-funnyqt/src/ttc15_model_execution_funnyqt/" #<buffer *magit: ~/Repos/uni/ttc15-model-execution-funnyqt/*>)
	       13641360
	       ("/home/horn/Repos/uni/ttc15-model-execution-funnyqt/test/model/" #<buffer *magit: ~/Repos/uni/ttc15-model-execution-funnyqt/*>)
	       13725948
	       ("/home/horn/Repos/uni/ttc15-model-execution-funnyqt/test/ttc15_model_execution_funnyqt/" #<buffer *magit: ~/Repos/uni/ttc15-model-execution-funnyqt/*>)))
```

I think the killed status buffer values in the map are caused by myself killing the status buffer at some point in time.  BTW, why are the keys of the map numbers?  I guess those are some kind of inotify IDs or handles but wouldn't it be reasonable to have the directories as keys so that you don't have multiple handles on the same directory?

Anyway, the killed buffers are not the problem.  I can do `M-x magit-filenotify-stop-all` followed by re-enabling `magit-filenotify-mode` in the status buffer.  Then the map is clean again (one entry per directory in my project with an associated live status buffer), but still I get these tons of messages.

This is not just a cosmetical issue.  The revert/nothing to be done cycle takes about 3 seconds (and that's a pretty small repository) in which emacs is stuck, i.e., I can't move or type but have to wait.

**Comment by tsdh** [comment]
Ah, I know the culprit.  When latex compiles stuff, many files (the aux file, the log file, the pdf file, etc.) change all the time.  That is, when I just edit and save my tex file, I get one revert message.  But during compilation, tons of files change several times a second.

I guess this problem will also trigger if I have some "normal" programming project and recompile that where tons of `*.o` or `*.elc` files get written during compilation.

Well, the revert/nothing to be done message comes from `magit-refresh`.  So it seems magit filenotify calls it really on every change of some file in the repo. What I think it should do is to "compress" the refresh requests.  For example, it could collect the status buffers to be refreshed in a list (using `cl-pushnew` in order to have no duplicates), and spawn off an idle timer that will actually do the refresh.  If more requests come within a given period of time (say, N = 2 seconds), the timer is canceled and reactivated.  Of course, then the status buffer won't be up-to-date immediately but only after N seconds in the best case. In the worst case, it takes compilation-time + N seconds in order to be refreshed. But that seems reasonable to me.

**Comment by tsdh** [comment]
BTW, it seems I'm not the only one bitten by this.  The commit https://github.com/wiedzmin/magit-filenotify/commit/db01d37babe753a5fc782f69aa5c88754c50d8cc in @wiedzmin's fork deactivates notifications completely in large repos.

**Comment by tsdh** [comment]
@ruediger, @tarsius Can anyone have a look at my PR #12? I'd also volunteer to help maintaining `magit-filenotify.el` if you feel that your time is currently too limited.

**Comment by ruediger** [comment]
I'm looking at it but I probably won't have time before the weekend to really test it.

**Comment by tsdh** [comment]
@ruediger Great, thanks.  I just added another commit for reusing the timer instead of creating a new one.  Now I can use magit-filenotify even with really large repositories such as the linux kernel.  The only thing which takes a bit is the initial creation of the magit status buffer, but I don't think that's caused by magit-filenotify.  And even if it was, it's not the result of my patches.

**Comment by tsdh** [comment]
@ruediger Any news on this front?  I use this daily (and now with inotify instead of gfilenotify where I've just found and fixed another bug which master still has in https://github.com/tsdh/magit-filenotify/commit/ee71ea069a69fd77577d41301faff0a52ece1df7) and it works fine.

**Comment by tsdh** [comment]
@ruediger I've squashed all the individual commits in my PR into one to make it easier to review.
