### ISSUE TITLE
"Too many open files" error on OSX, can't recover

### ISSUE THREAD

**Issue by simonmichael** [magit/magit-filenotify#17]
On OSX El Capitan with homebrew emacs HEAD started from dock icon and recent magit/magit-filenotify, I started getting "apply: Opening null device: Too many open files" errors when I try to refresh the magit status buffer, or kill it. M-x list-processes and ps didn't show any file notify process I could kill. Temporarily increasing kern.maxfiles[perproc] with sysctl didn't help. Had to restart emacs.

**Comment by ruediger** [comment]
Sounds like an issue with the file notification support on OSX, which sounds unsurprising considering how shitty OSX's APIs for this are. Especially watching of directories seems to be poorly supported. How many files and directories are in the repo you are trying to watch?

I don't have access to OSX, so I can't help you debug this.

**Comment by DarwinAwardWinner** [comment]
For what it's worth, the following is a reasonable workaround for this on my machine:

```elisp
(define-advice magit-filenotify-start
    (:around (oldfun &rest args) turn-off-on-error)
  "Turn off if `file-notify-error' is encountered."
  (condition-case err
      (apply oldfun args)
    (file-notify-error
     (display-warning
      'magit-filenotify
      (format "Stopping magit-filenotify due to error: %S" err))
     (magit-filenotify-stop))))
```

Basically, if it hits a `file-notify-error` during `magit-filenotify-start`, it just runs `magit-filenotify-stop`. (It should probably do some other things, like turn the mode off, but this works for now.)
