### ISSUE TITLE
file watching not possible, no file descriptor left: 207

### ISSUE THREAD

**Issue by pvinis** [magit/magit-filenotify#18]
I get this message when i try to enable the mode manually.
Im on OSX with Emacs 25

**Comment by ruediger** [comment]
Sounds like an issue with the file notification support on OSX, which sounds unsurprising considering how shitty OSX's APIs for this are. Especially watching of directories seems to be poorly supported. How many files and directories are in the repo you are trying to watch?

I don't have access to OSX, so I can't help you debug this.

**Comment by aiguofer** [comment]
Hmm running into this same issue on MacOS... Did you ever find a way to fix it? this is really messing with my Emacs flow.

Btw, same exact emacs config on ubuntu works perfectly

**Comment by dmocek** [comment]
I had the same problem and this fixed it for me:
sudo sysctl -w kern.maxfiles=524288

Answer from here: https://superuser.com/questions/630777/how-do-i-configure-fsnotifys-queue-size-watch-limit-on-osx
