### ISSUE TITLE
I would like to remove this repository from the Magit organisation

### ISSUE THREAD

**Issue by tarsius** [magit/magit-filenotify#19]
@ruediger

I don't think using this package is a good idea. As explained before, I don't think it is necessary and that it impacts performance negatively. I do acknowledged that it can be useful given certain workflows and I am not ruling out that Magit itself will one day gain similar functionality. But not before some major refactoring: currently refreshing a Magit buffer means recreating it from scratch, that and some other performance issues have to be addressed first. Until that has happened Magit will not gain support for something like this, maybe not even afterwards.

That's old news. The reason I want to remove this repository now, even though I was fine having it in the Magit organisation before, is that you still have not addressed the issues raised by users. This repository belonging to the Magit organisation implies some level of endorsement, and I am no longer willing to do that.

**Comment by tarsius** [comment]
I have created the temporary `out-of-magit` organisation to make it possible to transfer the repository to your user account and made you an owner. Please accept the invitation, I will then transfer the repository to that organisation and you can then transfer it from that organisation to your user account.

**Comment by tarsius** [comment]
I have just noticed that you haven't been very active on Github lately and have decided to move this repository to the Emacsorphanage until you get back. Please let me know when you have time to complete the move to your user account.

**Comment by ruediger** [comment]
The only issues raised were issues with OSX file notification support. Which is not an issue of magit-filenotify but both the OS and the way Emacs tries to implement a file notification library on top of it.

**Comment by ruediger** [comment]
What do I need to do to transfer the repo to my account? I don't appear to have permissions.

**Comment by tarsius** [comment]
I already gave to the highest possible per-repository permissions. It seems that is not enough and I will have to give you full access to the organisation.

Are you available right now to complete the move?

**Comment by tarsius** [comment]
> The only issues raised were issues with OSX file notification support. Which is not an issue of magit-filenotify but both the OS and the way Emacs tries to implement a file notification library on top of it.

Never-the-less moving seems like the best option considering that I was always rather skeptical and continue to recommend that users don't use this package. I hope I am not stepping on your toes too hard.

**Comment by ruediger** [comment]
I think the permissions have to be on the Organisation owning the repo. So maybe move it to the temp Org. Give me permissions on the Org and then I can move it to my account.

**Comment by ruediger** [comment]
Moved to my account

**Comment by tarsius** [comment]
Thanks!

I have updated Melpa and the Emacsmirror.
