### ISSUE TITLE
magit-filenotify breaks keybindings

### ISSUE THREAD

**Issue by M-Gregoire** [magit/magit-filenotify#21]
First  of all, thanks for proving your work to the community ! :+1: 

I'm facing a problem where loading `magit-filenotify` breaks some keybindings.

**Step to reproduce**
In `emacs -Q` :+1: 
```
(package-initialize)
(add-to-list 'package-archives
             '("melpa-stable" . "http://stable.melpa.org/packages/") t)
(package-refresh-contents)
(package-install 'magit)
(load "~/.emacs.d/etc/packages/magit-filenotify.el" nil t)
(setq smerge-command-prefix (kbd "C-c v"))
(smerge-mode)
```

**Problem**
The `C-c v` keybinding we just defined doesn't work : `C-c v is undefined`

**Comment by npostavs** [comment]
Does it work if you move the setting of `smerge-command-prefix` earlier, e.g.,

```elisp
(package-initialize)
(add-to-list 'package-archives
             '("melpa-stable" . "http://stable.melpa.org/packages/") t)
(package-refresh-contents)
(setq smerge-command-prefix (kbd "C-c v"))
(package-install 'magit)
(load "~/.emacs.d/etc/packages/magit-filenotify.el" nil t)
(smerge-mode)
```

**Comment by M-Gregoire** [comment]
Didn't though to try that ! Thank you, it does work :+1: .

**Comment by npostavs** [comment]
Right, so the problem is that setting `smerge-command-prefix` after `smerge` is already loaded has no effect. Loading `magit` also loads `smerge`, so you have to set it before installing/loading `magit` as well.

**Comment by M-Gregoire** [comment]
I didn't knew `magit` loaded `smerge` ! Thanks a lot for the help.
