### ISSUE TITLE
How to install this package on emacs < 24.4

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [magit/magit-filenotify#6]
I am getting updated version of the package which requires emacs 24.4 when I try to update all packages  using `packages-list-packages` and `U`. But it is failing because of emacs 24.4 constraint. `package-compute-transaction: Package `emacs-24.4' is unavailable`. How do I install it?

**Comment by ruediger** [comment]
Hi,
thanks for reporting the issue.  Are you using GNU Emacs 24.4 (or a newer snapshot)?  Please check by calling M-x emacs-version RET.

I recently changed the requirements to explicitly include the 24.4 dependency.  Maybe package.el does not support such a fine degree of version numbers.  I'll revert the change if this is true.

Regards,
Rüdiger

**Comment by prathamesh-sonpatki** [comment]
@ruediger I am using `24.3.1`.

**Comment by ruediger** [comment]
Only GNU Emacs 24.4 or newer with file notification is supported.

**Comment by prathamesh-sonpatki** [comment]
@ruediger Thats right. But the package's updated version is coming up with `packages-list-packages`. How I can avoid it on emacs < 24.4?

**Comment by tarsius** [comment]
> How I can avoid it on emacs < 24.4?

By uninstalling it.

Why do have it installed in the first place? (Maybe some starter-kit you are using includes it? It shouldn't do that, unless it explicitly states that 24.4 is required).

**Comment by prathamesh-sonpatki** [comment]
@tarsius Thanks. Removing the package solved it. I am not sure how I had it in first place. Might have installed myself. Please note that the version installed on my machine was working properly. The problem was with updated version which was coming from `packages-list-packages`.  I am not sure if we can specify that a specific version of package requires specific emacs version. Thanks for the help.

**Comment by tarsius** [comment]
> I am not sure if we can specify that a specific version of package requires specific emacs version.

Emacs just complained that your Emacs was to old, so this seems to be working :-)

**Comment by prathamesh-sonpatki** [comment]
Haha :) Thats true. But shouldn't `package-list-packages` not try to update in first place?

**Comment by quazgar** [comment]
Same here, it shows up in `package-list-packages`, with the same error, in Emacs 24.3.1, even though it's not installed in the first place.

**Comment by tarsius** [comment]
I am not an expert on `package.el` (I don't use it). You might want to ask about this on http://emacs.stackexchange.com/.
